import '../styles/globals.css'
import "../styles/LoginPage.css";
import "../styles/HomePage.css";
import Head from 'next/head';
import { AuthProvider } from '../contexts/auth';

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Registration</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthProvider>
        <Component {...pageProps} />
      </AuthProvider>
    </>
    
    );
}

export default MyApp
